import { posApiClient } from "./client";

export const CashSessionStatus = { Open: 1, Closed: 2 } as const;
export type CashSessionStatusValue = (typeof CashSessionStatus)[keyof typeof CashSessionStatus];

export interface OpenCashSessionInput {
  registerId: string;
  cashierId: string;
  openingBalance: number;
}

export interface CloseCashSessionInput {
  sessionId: string;
  closingBalance: number;
  expectedBalance: number;
  notes?: string | null;
}

/**
 * NOTE: the backend has no GET for cash sessions (no get-by-id, no list, no "current open
 * session for register X" lookup — see docs/API-GAPS.md). The frontend therefore persists the
 * session it opened in localStorage as the local source of truth for "is a session open right
 * now" within this browser. It cannot detect a session opened from another device/tab, and a
 * closed-but-not-yet-cleared localStorage entry could drift from server truth. This is a
 * documented limitation, not a bug.
 */
export const cashSessionsApi = {
  /** Returns the new session's ID. */
  open: (input: OpenCashSessionInput) => posApiClient.post<string>("/api/v1/cash-sessions/open", input),

  /** 204 No Content on success. */
  close: (input: CloseCashSessionInput) => posApiClient.post<void>("/api/v1/cash-sessions/close", input),
};

export interface TopProductLine {
  productId: string;
  sku: string;
  productName: string;
  quantitySold: number;
  revenue: number;
}

export interface DailySalesReport {
  storeId: string;
  reportDate: string;
  totalSalesCount: number;
  voidedSalesCount: number;
  grossRevenue: number;
  totalDiscount: number;
  totalTax: number;
  netRevenue: number;
  cashCollected: number;
  cardCollected: number;
  mobileMoneyCollected: number;
  otherCollected: number;
  topProductsJson: string;
  cashSessionSummaryJson: string;
  generatedAtUtc: string;
}

/**
 * NOTE: daily reports are generated by an overnight background job (UTC midnight, with a 7-day
 * catch-up window), NOT on demand. There is no "generate now" endpoint. In practice this means:
 * - Yesterday's report and older (within 7 days) will generally be available.
 * - TODAY's report will 404 with REPORT_NOT_FOUND until after the next UTC midnight run.
 * The Reports page defaults to yesterday's date for exactly this reason and explains the gap
 * rather than showing a misleading empty "$0" report for today.
 */
export const reportsApi = {
  getDailySales: (storeId: string, reportDate: string) =>
    posApiClient.get<DailySalesReport>("/api/v1/reports/daily-sales", { storeId, reportDate }),
};

export function parseTopProducts(json: string): TopProductLine[] {
  try {
    const parsed = JSON.parse(json);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}
